project:
  type: website
  output-dir: docs

website:
  title: "Matthew Levy - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Weekly Notes
        menu:
          - href: weekly-notes/week-01-notes.qmd
            text: Week 1
          - href: weekly-notes/week-02-notes.qmd
            text: Week 2
          - href: weekly-notes/week-03-notes.qmd
            text: Week 3
          - href: weekly-notes/week-04-notes.qmd
            text: Week 4
          - href: weekly-notes/week-05-notes.qmd
            text: Week 5
          - href: weekly-notes/week-06-notes.qmd
            text: Week 6
          - href: weekly-notes/week-07-notes.qmd
            text: Week 7
          - href: weekly-notes/week-09-notes.qmd
            text: Week 9
          - href: weekly-notes/week-10-notes.qmd
            text: Week 10
      - text: Labs
        menu:
          - href: labs/lab0/lab0_template.qmd
            text: "Lab 0: dyplr Basics"
          - href: labs/lab1/assignment1_template.qmd
            text: "Lab 1 Census Data Quality for Policy Decisions"
          - href: labs/lab2/Levy-Matthew-Assignment2.qmd
            text: "Lab 2: Spatial Analysis and Visualization"
     
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
